# Generated by Django 2.0.2 on 2018-03-15 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Nurse', 'Nurse'), ('Admin', 'Admin')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CompletedTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField()),
                ('date', models.DateField()),
                ('nurse', models.OneToOneField(limit_choices_to={'type': 'Nurse'}, on_delete=django.db.models.deletion.CASCADE, to='OKareApp.Account')),
            ],
        ),
        migrations.CreateModel(
            name='DailyTriage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('blood_pressure', models.IntegerField()),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('blood_sugar', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Nurses',
            fields=[
                ('nric', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='First Name', max_length=30)),
                ('last_name', models.CharField(default='Last Name', max_length=30)),
                ('mobile_no', models.IntegerField(default=0)),
                ('date_of_birth', models.DateTimeField(auto_now=True)),
                ('street', models.CharField(default='Street', max_length=128)),
                ('city', models.CharField(default='City', max_length=64)),
                ('state', models.CharField(default='State', max_length=32)),
                ('zip_code', models.CharField(default='Zip Code', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='NurseStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('help_requested', models.IntegerField()),
                ('help_administered', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('nric', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('ward', models.CharField(max_length=15)),
                ('bed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('recur_type', models.CharField(choices=[('Weekly', 'Weekly'), ('Daily', 'Daily'), ('Monthly', 'Monthly')], max_length=100, null=True)),
                ('start_time', models.TimeField()),
                ('duration', models.DurationField()),
                ('date', models.DateField(null=True)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='OKareApp.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ward', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='team',
            field=models.OneToOneField(on_delete=None, to='OKareApp.Teams'),
        ),
        migrations.AddField(
            model_name='dailytriage',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OKareApp.Patient'),
        ),
        migrations.AddField(
            model_name='completedtask',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='OKareApp.Task'),
        ),
        migrations.AddField(
            model_name='account',
            name='team',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OKareApp.Teams'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
