# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-18 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('OKareApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedtask',
            name='compldt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
