# Generated by Django 2.0.2 on 2018-03-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OKareApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurses',
            name='nurse_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nurses',
            name='nric',
            field=models.CharField(max_length=9),
        ),
    ]
