# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-27 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OKareApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationBell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('Broadcast', 'Broadcast'), ('Response', 'Response'), ('Request', 'Request'), ('Task', 'Task')], max_length=100, null=True)),
                ('status', models.BooleanField(default=True)),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OKareApp.Account')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OKareApp.Task')),
            ],
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='time_created',
            field=models.DateTimeField(),
        ),
    ]
