# Generated by Django 2.0.3 on 2018-03-16 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OKareApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helper', models.ForeignKey(limit_choices_to={'type': 'Nurse'}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='OKareApp.Account')),
                ('requester', models.ForeignKey(limit_choices_to={'type': 'Nurse'}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='OKareApp.Account')),
            ],
        ),
        migrations.CreateModel(
            name='OngoingTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nurse', models.OneToOneField(limit_choices_to={'type': 'Nurse'}, on_delete=django.db.models.deletion.CASCADE, to='OKareApp.Account')),
            ],
        ),
        migrations.AlterField(
            model_name='completedtask',
            name='nurse',
            field=models.ForeignKey(limit_choices_to={'type': 'Nurse'}, on_delete=django.db.models.deletion.CASCADE, to='OKareApp.Account'),
        ),
        migrations.AlterField(
            model_name='completedtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OKareApp.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OKareApp.Patient'),
        ),
        migrations.AddField(
            model_name='ongoingtask',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='OKareApp.Task'),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OKareApp.Task'),
        ),
    ]
