# Generated by Django 2.0.2 on 2018-03-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OKareApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurse',
            name='team',
        ),
        migrations.AddField(
            model_name='nurse',
            name='city',
            field=models.CharField(default='City', max_length=64),
        ),
        migrations.AddField(
            model_name='nurse',
            name='date_of_birth',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='nurse',
            name='mobile_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nurse',
            name='state',
            field=models.CharField(default='State', max_length=32),
        ),
        migrations.AddField(
            model_name='nurse',
            name='street',
            field=models.CharField(default='Street', max_length=128),
        ),
        migrations.AddField(
            model_name='nurse',
            name='zip_code',
            field=models.CharField(default='Zip Code', max_length=10),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='first_name',
            field=models.CharField(default='First Name', max_length=30),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='last_name',
            field=models.CharField(default='Last Name', max_length=30),
        ),
    ]
