# Generated by Django 2.0.3 on 2018-03-30 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OKareApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationbell',
            name='help_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OKareApp.HelpRequest'),
        ),
    ]
