# Generated by Django 2.0.3 on 2018-03-18 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OKareApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequestnotification',
            name='help_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OKareApp.HelpRequest'),
        ),
    ]
