# Generated by Django 2.0.3 on 2018-03-15 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OKareApp', '0002_auto_20180315_1528'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nurses',
        ),
        migrations.AddField(
            model_name='account',
            name='city',
            field=models.CharField(default='City', max_length=64),
        ),
        migrations.AddField(
            model_name='account',
            name='date_of_birth',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='account',
            name='phoneNo',
            field=models.DecimalField(decimal_places=0, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='state',
            field=models.CharField(default='State', max_length=32),
        ),
        migrations.AddField(
            model_name='account',
            name='street',
            field=models.CharField(default='Street', max_length=128),
        ),
        migrations.AddField(
            model_name='account',
            name='zip_code',
            field=models.CharField(default='Zip Code', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Hygiene', 'Hygiene'), ('Medical_Care', 'Medical Care'), ('Therapy', 'Therapy'), ('Food', 'Food')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OKareApp.Teams'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='team',
            field=models.ForeignKey(on_delete=None, to='OKareApp.Teams'),
        ),
    ]
