# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-31 00:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('OKareApp', '0002_notificationbell_help_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationbell',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
