# Generated by Django 2.0.3 on 2018-03-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OKareApp', '0002_auto_20180316_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='day',
            field=models.CharField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], max_length=20),
        ),
    ]
