# Generated by Django 2.0.3 on 2018-03-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OKareApp', '0003_auto_20180315_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Hygiene', 'Hygiene'), ('Medical_Care', 'Medical Care'), ('Therapy', 'Therapy'), ('Food', 'Food'), ('Misc', 'Miscallenous')], default='Misc', max_length=100),
        ),
    ]
