# Generated by Django 2.0.3 on 2018-03-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OKareApp', '0004_auto_20180315_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='id',
        ),
        migrations.AddField(
            model_name='account',
            name='nric',
            field=models.CharField(default='S1234567G', max_length=9, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
