# Generated by Django 2.0.3 on 2018-03-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OKareApp', '0005_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.CharField(default='City', max_length=64),
        ),
        migrations.AddField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='phoneNo',
            field=models.DecimalField(decimal_places=0, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='state',
            field=models.CharField(default='State', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='street',
            field=models.CharField(default='Street', max_length=128),
        ),
        migrations.AddField(
            model_name='patient',
            name='zip_code',
            field=models.CharField(default='Zip Code', max_length=10),
        ),
    ]
