# Generated by Django 2.0.3 on 2018-03-17 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OKareApp', '0007_auto_20180317_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='helper',
            field=models.ForeignKey(limit_choices_to={'type': 'Nurse'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='OKareApp.Account'),
        ),
    ]
