# Generated by Django 2.0.3 on 2018-03-18 11:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('OKareApp', '0008_auto_20180317_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpRequestNotificaton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='helprequest',
            name='acknowledgement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ongoingtask',
            name='assigned_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='helprequestnotificaton',
            name='help_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='OKareApp.HelpRequest'),
        ),
        migrations.AddField(
            model_name='helprequestnotificaton',
            name='reader',
            field=models.ForeignKey(limit_choices_to={'type': 'Nurse'}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='OKareApp.Account'),
        ),
    ]
