# Generated by Django 2.0.3 on 2018-03-18 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OKareApp', '0009_auto_20180318_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='ongoing_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OKareApp.OngoingTask'),
        ),
    ]
