# Generated by Django 2.0.3 on 2018-03-18 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OKareApp', '0010_helprequest_ongoing_task'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HelpRequestNotificaton',
            new_name='HelpRequestNotification',
        ),
    ]
